---
title: 'ESM 203: Assignment 3'
author: "Madeline Gorchels"
date: "11/15/2018"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,include=FALSE}
library(tidyverse)
library(kableExtra)
library(knitr)

gw_mgmt = read_csv("ESM203Assn3.csv")

```

```{r,include=FALSE}
##Part 1: Making a regression for the outflow

outflow_reg = lm(outflow~year, data=gw_mgmt)

outflow_reg$fitted #this will show me the regression lines values for the points I put in. Unhelpful in this case 

#now I'm going to use my model 

outflow_reg$coefficients # shows my y intercept and slope

#This uses the model automatically
coef(outflow_reg)[1] #this is the intercept
coef(outflow_reg)[2] #this is the slope

coef(outflow_reg)[1]+coef(outflow_reg)[2]*2002 #example using 2002

#apparently there is a neater way
predict(outflow_reg,list(year=2002)) # for a single value
outflow_mod = predict(outflow_reg,data.frame(year=c(2000:2050))) #this generates a new data frame using the years between 2000 and 2050.

#View(outflow_mod)
```

```{r,include=FALSE}
##Part 2. Making an Inflow Model 

inflow_reg = lm(inflow~year, data=gw_mgmt)

inflow_reg$fitted #this will show me the regression lines values for the points I put in. Unhelpful in this case 

#now I'm going to use my model 
inflow_reg$coefficients # shows my y intercept and slope

#This uses the model automatically
coef(inflow_reg)[1] #this is the intercept
coef(inflow_reg)[2] #this is the slope

coef(inflow_reg)[1]+coef(inflow_reg)[2]*2002 #example using 2002

#apparently there is a neater way
predict(inflow_reg,list(year=2002)) # for a single value
inflow_mod = predict(inflow_reg,data.frame(year=c(2000:2050))) #this is getting exciting
#View(inflow_mod)
```
```{r, include=FALSE}
netloss = predict(outflow_reg,data.frame(year=c(2000:2050)))-predict(inflow_reg,data.frame(year=c(2000:2050)))

lowerCI = 190
  for (i in 1:50) {lowerCI[i+1] = lowerCI[i] - netloss[i]}
mean = 350
  for (i in 1:50) {mean[i+1] = mean[i] - netloss[i]}
upperCI = 550
  for (i in 1:50) {upperCI[i+1] = upperCI[i] - netloss[i]}

mean_gw = 350
gw_df = data.frame(matrix(ncol = 7, nrow = 51))
x = c("year", "outflow", "inflow", "netloss", "reservoir_190", "resevoir_350", "resevoir_550")
colnames(gw_df) = x
gw_model = gw_df %>% 
  mutate(year = 2000:2050) %>% 
  mutate(outflow = predict(outflow_reg,data.frame(year=c(2000:2050)))) %>% 
  mutate(inflow = predict(inflow_reg,data.frame(year=c(2000:2050)))) %>%
  mutate(netloss = outflow-inflow) %>% 
  mutate(resevoir_190 = lowerCI) %>% 
  mutate(resevoir_350 = mean) %>% 
  mutate(resevoir_550 = upperCI)





```


```{r, echo=FALSE}

line_comp = ggplot(gw_model, aes(x = year))+
  geom_line(aes(y = resevoir_350, colour = "green"), size=1)+
  geom_line(aes(y = resevoir_190, color = "b"), size=1)+
  geom_line(aes(y = resevoir_550, color = "blue"), size=1)+
  geom_line(aes(y = 0), linetype = "dashed")+
  theme_classic()+
  scale_color_grey()+
  ylab(bquote("Groundwater Resources (billions m"^"3"*")"))+
  xlab("Year")+
  scale_y_continuous(expand = c(0,0))+
  scale_x_continuous(expand = c(0,0.5))+
  scale_color_discrete(name = "Scenario", labels = c("Lower Estimate", "Mean Estimate", "Upper Estimate"))
  

line_comp

```

